In [1]:
# # Q1

# Yes, there is a difference in the data types of variables list_ and array_list. The variable list_ is a 
# Python list, while array_list is a NumPy array.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [3]:
# Q2

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
# # Q3
# Yes, there will be a difference in the data type of the elements present in list_ and array_list due to the 
# specified dtype parameter as int during the creation of array_list. 
# The elements in array_list will be converted to integers.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [8]:
# Q4

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print('Shape is : ', num_array.shape)
print('SIze is : ', num_array.size)

Shape is :  (2, 3)
SIze is :  6


In [13]:
# Q5

import numpy as np

arr = np.zeros((3,3))

print('Array is : ', arr)
print('Size is : ', arr.size)
print('Shape is : ', arr.shape)

Array is :  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Size is :  9
Shape is :  (3, 3)


In [18]:
# Q6

identity_matrix = np.eye(5)

print('Identity Matrix is : \n', identity_matrix)
print('Shape is : ', identity_matrix.shape)

Identity Matrix is : 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Shape is :  (5, 5)
